const result = await Bun.build({
  entrypoints: ["browser/billing.ts"],
  target: "browser",
  minify: true,
});
if (!result.success || result.outputs.length !== 1)
  throw new AggregateError(result.logs, "Billing App build failed");
const script = (await result.outputs[0]!.text()).replaceAll(
  "</script",
  "<\\/script",
);
const css = `:root{color-scheme:light dark;font:14px/1.5 system-ui,sans-serif}*{box-sizing:border-box}body{margin:0}main{padding:18px;max-width:980px}h1{font-size:20px;margin:0 0 12px}button,input,select{font:inherit;padding:8px;border:1px solid #8888;border-radius:6px}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}.controls{display:flex;gap:12px;align-items:end;flex-wrap:wrap}label{display:grid;gap:4px}.cards{display:flex;gap:12px;flex-wrap:wrap}.cards div{border:1px solid #8885;border-radius:8px;padding:12px;min-width:130px}.cards dd{font-size:26px;font-weight:600;margin:0}.table-scroll{max-width:100%;overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #8885;overflow-wrap:anywhere}.note{opacity:.8;font-size:12px}summary{cursor:pointer;margin-top:12px}`;
await Bun.write(
  "src/billingApp.generated.ts",
  `// Generated by scripts/build-apps.ts; do not edit.\nexport const billingAppScript: string=${JSON.stringify(script)};\nexport const billingAppCss: string=${JSON.stringify(css)};\n`,
);

export {};

const workflow = await Bun.build({
  entrypoints: ["browser/workflow.ts"],
  target: "browser",
  minify: true,
});
if (!workflow.success || workflow.outputs.length !== 1)
  throw new AggregateError(workflow.logs, "Workflow App build failed");
await Bun.write(
  "src/workflowApp.generated.ts",
  `// Generated by scripts/build-apps.ts; do not edit.\nexport const workflowAppScript: string=${JSON.stringify((await workflow.outputs[0]!.text()).replaceAll("</script", "<\\/script"))};\nexport const workflowAppCss: string=${JSON.stringify(css + "body{background:var(--color-background-primary,Canvas);color:var(--color-text-primary,CanvasText)}main{overflow-wrap:anywhere}select{width:100%;max-width:100%;background:var(--color-background-secondary,Canvas);color:inherit}button{margin:6px 6px 0 0}[hidden]{display:none!important}section{border:1px solid #8885;border-radius:12px;padding:16px;margin:12px 0}h2{font-size:17px}button{background:var(--color-background-secondary,ButtonFace);color:inherit}")};\n`,
);

const selection = await Bun.build({
  entrypoints: ["browser/setupSelection.ts"],
  target: "browser",
  minify: true,
});
if (!selection.success || selection.outputs.length !== 1)
  throw new AggregateError(selection.logs, "Setup selection build failed");
await Bun.write(
  "src/setupSelection.generated.ts",
  `// Generated by scripts/build-apps.ts; do not edit.\nexport const setupSelectionScript: string=${JSON.stringify((await selection.outputs[0]!.text()).replaceAll("</script", "<\\/script"))};\n`,
);

const action = await Bun.build({
  entrypoints: ["browser/actionWorkflow.ts"],
  target: "browser",
  minify: true,
});
if (!action.success || action.outputs.length !== 1)
  throw new AggregateError(action.logs, "Action App build failed");
await Bun.write(
  "src/actionWorkflow.generated.ts",
  `// Generated; do not edit.\nexport const actionWorkflowScript:string=${JSON.stringify((await action.outputs[0]!.text()).replaceAll("</script", "<\\/script"))};\n`,
);
